### ISSUE TITLE
Customized session in each request

### ISSUE THREAD

**Issue by ricardo8990** [cuenca-mx/cuenca-python#100]
There are cases where you might have to use temporary credentials in order to perform an operation. For instance, when you need to authenticate a user for certain request.

Right now there's already a way to override the current header by doing:
```python
import cuenca

# Configure user credentials
cuenca.session.configure(
    api_key=USER_API_KEY,
    api_secret=USER_SECRET_KEY
)

# Perform operation
cuenca.Card.all(user_id='USlskdjflskdjf')

# Return to default credentials
cuenca.session.configure(
    api_key =CUENCA_API_KEY,
    api_secret=CUENCA_SECRET_KEY
)
```

But it would be clearer and safer doing something like:
```python
import cuenca

with cuenca.configure(
        api_key=USER_API_KEY,
        api_secret=USER_SECRET_KEY
    ) as cuenca_user:
    cuenca_user.Card.all(user_id='USlskdjflskdjf')
```

This is specially useful in `core` which has to make requests on behalf of users to authenticate with their credentials.

**Comment by ricardo8990** [comment]
@matin @alexviquez @felipaoo what do you think about it?

**Comment by matin** [comment]
That's not thread-safe. If you need to be able to change auth by request, then there should be a way to set the auth on the request. However, calling `.configure()` changes the configuration the `client` object stored at the module level, which affect other threads running inside of the same process.

This is the trade-off of the design approach for how `client` is instantiated. It simplifies the 99% scenario, but it means not having an interface to create a new client per request. In `stpmex`, you'd have been able to create a new `client`.

**Comment by ricardo8990** [comment]
That's right. I don't see a way to use a Context Manager without changing the way `Session` is instantiated or locally importing the library on each request. Then, what about adding optional parameters specifying the credentials to be used. Something like:

```python
import cuenca

cards = cuenca.Cards.all(user_id='USlskdjflskdjf', api_key=USER_API_KEY, api_secret=USER_SECRET_KEY)
```

This would override the `auth` parameter in the request and it would only apply for this request.

**Comment by matin** [comment]
Why not pass in a `Session` object instead?

```python
cuenca.Card.all(session=sess)
```

**Comment by ricardo8990** [comment]
Sounds good 👍🏽
